package controllers;

public enum Actions {
ACTION_ACOMODATION, ACTION_FLIES, ACTION_PACKAGES, ACTION_IMBATIBLES, ACTION_GETAWAYS, ACTION_ACTIVITIES, ACTION_CARS, ACTION_DISNEY, ACTION_SECURES, ACTION_TRANSFERS, ACION_CRUISES
}
